name: "Release"

on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: oven-sh/setup-bun@v2
      - run: npm i -g pnpm@11.0.8
      - run: |
          pnpm dlx \
             --package semantic-release@25.0.2 \
             --package conventional-changelog-conventionalcommits \
             --package @semantic-release/git \
             --package @semantic-release/exec \
              semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
